-- EnergIA Sur · Contexto del hogar
-- Ejecutar en el SQL Editor de Supabase, despues de 0012_event_time_order.sql.
--
-- Hasta ahora la app sabia que hay un medidor y cuanto mide, pero no que hay
-- del otro lado del cable. Estas tablas guardan el ambiente donde vive el
-- medidor: que tipo de vivienda es, que ambientes tiene y que aparatos hay en
-- cada uno.
--
-- Con eso, las recomendaciones pueden dejar de ser genericas ("bajá 2 kWh por
-- dia") y pasar a nombrar cosas concretas del hogar. Es tambien la base sobre
-- la que despues se puede apoyar un modelo que estime que aparato explica cada
-- pico de consumo.
--
-- Se guarda SOLO la presencia de cada aparato, no su potencia ni su frecuencia
-- de uso: nadie sabe de memoria cuantos watts consume su heladera, y un
-- formulario que lo pide se abandona. La potencia tipica, si hace falta, sale
-- de una tabla de referencia en el codigo.

-- --------------------------------------------------------------------------
-- Vivienda: una fila por medidor.
-- --------------------------------------------------------------------------
create table if not exists public.home_contexts (
  device_id     text primary key references public.meters(device_id) on delete cascade,
  dwelling_type text not null,
  floors        integer not null default 1,
  created_at    timestamptz not null default now(),
  updated_at    timestamptz not null default now()
);

alter table public.home_contexts
  drop constraint if exists home_contexts_dwelling_type_valid;

alter table public.home_contexts
  add constraint home_contexts_dwelling_type_valid
  check (dwelling_type in ('casa', 'depto'));

-- Un limite alto pero finito: atrapa el tipeo sin discutirle al usuario.
alter table public.home_contexts
  drop constraint if exists home_contexts_floors_range;

alter table public.home_contexts
  add constraint home_contexts_floors_range
  check (floors between 1 and 50);

comment on table public.home_contexts is
  'Tipo de vivienda donde esta instalado cada medidor. Una fila por medidor;
   su ausencia significa que el usuario todavia no cargo el contexto.';

-- --------------------------------------------------------------------------
-- Ambientes: los que el usuario nombro (Cocina, Living, Dormitorio 1...).
-- --------------------------------------------------------------------------
create table if not exists public.home_rooms (
  id         bigint generated by default as identity primary key,
  device_id  text not null references public.meters(device_id) on delete cascade,
  name       text not null,
  position   integer not null default 0,
  created_at timestamptz not null default now()
);

-- Dos ambientes con el mismo nombre en la misma casa serian indistinguibles
-- para el usuario, asi que no tiene sentido permitirlos.
create unique index if not exists home_rooms_device_name_key
  on public.home_rooms (device_id, lower(name));

create index if not exists home_rooms_device_idx
  on public.home_rooms (device_id, position);

comment on column public.home_rooms.position is
  'Orden en que el usuario los cargo. Se respeta al mostrarlos para que la
   pantalla no cambie de orden entre visitas.';

-- --------------------------------------------------------------------------
-- Aparatos por ambiente. `appliance_id` es una clave del catalogo fijo que
-- vive en el codigo (src/lib/home-catalog.ts), no un texto libre.
-- --------------------------------------------------------------------------
create table if not exists public.home_appliances (
  id           bigint generated by default as identity primary key,
  room_id      bigint not null references public.home_rooms(id) on delete cascade,
  appliance_id text not null,
  created_at   timestamptz not null default now()
);

-- El mismo aparato marcado dos veces en el mismo ambiente es la misma
-- informacion repetida: hoy se guarda presencia, no cantidad.
create unique index if not exists home_appliances_room_appliance_key
  on public.home_appliances (room_id, appliance_id);

create index if not exists home_appliances_room_idx
  on public.home_appliances (room_id);

comment on table public.home_appliances is
  'Presencia de un aparato en un ambiente. Sin potencia ni frecuencia de uso:
   se pidio deliberadamente el minimo que el usuario puede responder sin
   dudar. Si mas adelante hace falta cantidad, va como columna nueva.';

-- --------------------------------------------------------------------------
-- RLS activo y sin politicas, igual que el resto de las tablas: nadie lee
-- esto con la clave publica. El servidor resuelve el usuario desde la cookie
-- y filtra por el medidor que le pertenece, usando la service role key.
-- --------------------------------------------------------------------------
alter table public.home_contexts   enable row level security;
alter table public.home_rooms      enable row level security;
alter table public.home_appliances enable row level security;
